version: '3'

services:
  php:
    container_name: "php-test"
    build:
      context: ./docker/php
    environment:
      - APP_ENV=${APP_ENV}
      - APP_SECRET=${APP_SECRET}
    volumes:
      - ./:/var/www
    depends_on:
      - mariadb

  nginx:
    container_name: "nginx-test"
    build:
      context: ./docker/nginx
    volumes:
      - ./:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/logs:/var/log
    depends_on:
      - php
    ports:
      - "80:80"

  mariadb:
    image: mariadb:10.2.7
    container_name: "mariadb-test"
    ports:
      - "9345:3306"
    restart: always
    environment:
      MYSQL_DATABASE: main
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - "./docker/db:/var/lib/mysql"

  phpmyadmin:
    image: phpmyadmin
    container_name: "phpmyadmin-test"
    restart: always
    depends_on:
      - mariadb
    ports:
      - "8080:80"

  #sudo chmod -R 777 .